### ISSUE TITLE
Biarin GitHub Actions yang compile projectnya

### ISSUE THREAD

**Issue by andraantariksa** [luthfisauqi17/luthfisauqi17.github.io#1]
1. Signup GitHub Actions: https://github.com/features/actions

2. Buat file `.github/workflows/gh-pages.yml`

```
name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      # with:
      #   submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.2.2
      with:
        hugo-version: '0.58.3'
        # extended: true

    - name: Build
      run: hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
```
3. Project directorynya isinya cukup projectnya aja, nggak perlu hasil compile (Folder `public` di project masukin ke `.gitignore` biar nggak kecommit)

Jadi biar nggak harus compile ulang tiap mau commit, biar GitHub yang compile

https://github.com/marketplace/actions/hugo-setup-action
